### ISSUE TITLE
使用llvm 默认链接参数

### ISSUE THREAD

**Issue by zhangn1985** [12101111/12101111.github.io#1]
在你的文章中指明：
```
export LDFLAGS="-fuse-ld=lld -rtlib=compiler-rt -flto=thin"
```
但是实际上在链接C++代码的时候，还是会报unwind函数找不到，这时候需要修改为
```
export LDFLAGS="-fuse-ld=lld -rtlib=compiler-rt -flto=thin -lunwind"
```

另外：
```
sed -i '8iset(CMAKE_C_COMPILER_WORKS 1)\nset(CMAKE_CXX_COMPILER_WORKS 1)\nset(CMAKE_SIZEOF_VOID_P 8)\n' CMakeLists.txt
```
这个修改可以变成cmake预定义
```
-DCMAKE_C_COMPILER_WORKS=1 -DCMAKE_CXX_COMPILER_WORKS=1 -DCMAKE_SIZEOF_VOID_P=8
```
其余类似，除了libcxx。

另外，我在尝试cross compile llvm for aarch64 with musl，不知道cmake 怎么配置。按照libcxxabi等的方式配置cmake，会自动去寻找host的/lib/ld-musl-aarch64.so.1

**Comment by 12101111** [comment]
fixed by https://github.com/12101111/12101111.github.io/commit/32de5806bdf22a09b602781acd175ea8804bb076
